PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select  ?concept ?Area ?Type ?Typename ?id
where {
{select *
where {
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasModel ?mprp .
?mprp rdf:type ?Type.
BIND(xsd:string("Model Type") as ?Area)}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasReport ?mprp .
?mprp rdf:type ?Type.
BIND(xsd:string("Report Type") AS ?Area)
}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasProcedure ?mprp .
?mprp rdf:type ?Type.
bind(xsd:string ("Procedure Type") as ?Area)}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasPolicy ?mprp .
?mprp rdf:type ?Type.
bind(xsd:string ("Policy Type") as ?Area)}
UNION
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasProduct ?mprp.
?mprp rdf:type ?Type.
bind(xsd:string ("Product") as ?Area)}
}}
?concept rdfs:label ?conceptName .
?mprp rdfs:label ?connections .
?Type rdfs:label ?Typename.

bind(rand() AS ?id).

}