PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Industry ?Wholesale_Finance ?CRE ?Equipment_Finance ?Credit_Card ?Auto_Loan
WHERE{

{SELECT ?Industry (SUM(?1) AS ?11)( SUM(?2) AS ?22)(SUM(?3) AS ?33) (SUM(?4) AS ?44) (SUM(?5) AS ?55)
WHERE {
?Top cst:tophasInd ?Industry
FILTER(?Top = cst:Topic310)
?Industry pb:IndustryRelatedtoSegment ?Seg.
?Top rdfs:label ?Topic.
?Industry rdfs:label ?Indus .
?Seg rdfs:label ?Segment.
BIND(IF(?Seg = pb:WholesaleFinance,1,0) AS ?1)
BIND(IF(?Seg = pb:CommercialRealEstate,1,0) AS ?2)
BIND(IF(?Seg = pb:EquipmentFinance,1,0) AS ?3)
BIND(IF(?Seg = pb:CreditCard,1,0) AS ?4)
BIND(IF(?Seg = pb:AutoLoan,1,0) AS ?5)

}
GROUP BY ?Industry
}
BIND(IF(?11 = 1,xsd:string("Yes"),xsd:string("No ")) AS ?Wholesale_Finance)
BIND(IF(?22 = 1,xsd:string("Yes"),xsd:string("No ")) AS ?CRE)
BIND(IF(?33 = 1,xsd:string("Yes"),xsd:string("No")) AS ?Equipment_Finance)
BIND(IF(?44 = 1,xsd:string("Yes"),xsd:string("No ")) AS ?Credit_Card)
BIND(IF(?55 = 1,xsd:string("Yes"),xsd:string("No ")) AS ?Auto_Loan)}