PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.mindparabole.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT 
?Month_Name ?Month2 (COUNT( DISTINCT ?mt) AS ?Number_of_Meetings) 
(COUNT(DISTINCT ?AI)AS ?Number_of_Action_Items_Closed)
(COUNT(DISTINCT ?Attendees)AS ?Number_of_Attendees)
(COUNT(DISTINCT ?Reg)AS ?Number_of_Regrets)
WHERE{

{SELECT *
WHERE{
   
 {SELECT *
        WHERE{
        ?mt rdf:type mt:Meeting_Name.
        ?mt mt:Date ?Date.
        BIND(replace(?Date,"_","-") AS ?Date2)
        BIND(xsd:date(?Date2) AS ?Date3)
        BIND(month(?Date3) AS ?Month)
        }}
        UNION
        {SELECT *
        WHERE{
        ?AI rdf:type CDE:Action_Item.
        OPTIONAL{?AI CDE:ActionItemHasStatus ?status.}
        FILTER(?status = "closed"||?status = "Closed")
        OPTIONAL{?AI CDE:ActionItemHasResolutionDate ?Date.}
        BIND(replace(?Date,"_","-") AS ?Date2)
        BIND(xsd:date(?Date2) AS ?Date3)
        BIND(month(?Date3) AS ?Month)
        }}
        UNION
        {SELECT *
        WHERE{
        ?mt3 rdf:type mt:Meeting_Name.
        ?mt3 mt:Date ?Date.
        BIND(replace(?Date,"_","-") AS ?Date2)
        BIND(xsd:date(?Date2) AS ?Date3)
        BIND(month(?Date3) AS ?Month)
        ?mt3 mt:has_Attendees ?Attendees.
        ?mt3 mt:has_Regrets ?Reg.
        FILTER(?Reg != cit:None)
        }}
        BIND (
      IF(?Month = 1, 01, 
       IF(?Month = 2, 02,
        IF(?Month = 3, 03,
         IF(?Month = 4, 04,
          IF(?Month = 5, 05,
           IF(?Month = 6, 06,
            IF(?Month = 7, 07, 
            IF(?Month = 8,08,
            IF(?Month = 9,09,
            IF(?Month = 10,10,
            IF(?Month = 11,11,
            IF(?Month = 12, 12,"Unknown")
      ))))))))))) AS ?Month2
    )}}
BIND (
      IF(?Month2 = 01, "January", 
       IF(?Month2 = 02, "February",
        IF(?Month2 = 03, "March",
         IF(?Month2 = 04, "April",
          IF(?Month2 = 05, "May",
           IF(?Month2 = 06, "June",
            IF(?Month2 = 07, "July", 
            IF(?Month2 = 08,"August",
            IF(?Month2 =09,"September",
            IF(?Month2 = 10,"October",
            IF(?Month2 = 11,"November",
            IF(?Month2 = 12, "December","Unknown")
      ))))))))))) AS ?Month_Name

)}
GROUP BY ?Month_Name ?Month2
ORDER BY ?Month2
