PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.mindparabole.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT ?Per ?dr_name
WHERE{

{SELECT (SUM(?com) AS ?Com)(COUNT(?ip) AS ?Total)?dr_name
 WHERE{
    ?dr rdf:type pb:Data_Request .
    ?dr rdfs:label ?dr_name.
    ?model rdf:type pb:Model.
    FILTER(?model = pb:SME_PD_Model)
    ?model pb:Model_has_DR ?dr.
    ?dr pb:DataReq_has_input ?ip.
    ?ip pb:Modelinputstatus ?st.
    BIND(IF(?st = "Complete",1,0) AS ?com)
    
}
GROUP BY ?dr_name}
BIND( (?Com/?Total) * 100 AS ?la)
BIND(round(?la) AS ?Per)

}
