PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT 
?label
	(COUNT(?identifyStatus) AS ?identifyData) 
	(COUNT(?identifyCStatus) AS ?collectData) 
	(COUNT(?identifyFStatus) AS ?finalDisclosure) 
	(COUNT(?identifyGStatus) AS ?gapRemediation) 
	(COUNT(?identifyGaStatus) AS ?identifyGap)
	(COUNT(?linkDStatus) AS ?linkData)
	(COUNT(?techLStatus) AS ?techLoadToReport)
	(COUNT(?validationRStatus) AS ?validationRule)
WHERE {
 	?reportField rdf:type mpb-root-main:ReportField .
	?reportField mpb-root-main:isPartOfReportForm ?reportForm .
	?reportForm mpb-root-main:isPartOfReportSub_Schedule ?reportSub_Schedule .
	?reportSub_Schedule  mpb-root-main:isPartOfReportSchedule ?reportSchedule .
	?reportSub_Schedule rdfs:label ?label.	
OPTIONAL {?reportField mpb-root-main:hasIdentifyDataStatus ?identifyStatus .}
	OPTIONAL {?reportField mpb-root-main:hasCollectDataActivityStatus ?identifyCStatus .}
	OPTIONAL {?reportField mpb-root-main:hasFinalDisclosure ?identifyFStatus .}
	OPTIONAL {?reportField mpb-root-main:hasGapRemediationStatus ?identifyGStatus .}
	OPTIONAL {?reportField mpb-root-main:hasIdentifyGapStatus ?identifyGaStatus .}
	OPTIONAL {?reportField mpb-root-main:hasLinkDataStatus ?linkDStatus.}
	OPTIONAL {?reportField mpb-root-main:hasTechLoadToReportStatus ?techLStatus.}
	OPTIONAL {?reportField mpb-root-main:hasValidationRulesStatus ?validationRStatus.}
}
GROUP BY ?label