PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hp: <http://mindparabole.com/finance/parabole#>


SELECT DISTINCT  ?Pro ?Product ?Segment ?Seg
WHERE{

{SELECT ?mprp ?Pro ?Product
WHERE {
?mprp rdfs:subClassOf ?class.
?class owl:allValuesFrom|owl:someValuesFrom ?val; owl:onProperty hp:hasProduct .
?val owl:oneOf/rdf:rest*/rdf:first  ?pro2.
?Pro rdf:type ?pro2; rdfs:label ?Product.
}}
{SELECT ?mprp2 ?Seg ?Segment
WHERE {
?mprp2 rdfs:subClassOf ?class2.
?class2 owl:allValuesFrom|owl:someValuesFrom ?val2; owl:onProperty hp:hasSegment .
?val2 owl:oneOf/rdf:rest*/rdf:first  ?seg.
?Seg rdf:type ?seg; rdfs:label ?Segment.
}}
FILTER(?mprp=?mprp2)
FILTER(?Seg IN( pb:CommercialIndustrial,pb:CreditCardDivision ,pb:ABCAssetManagementGroup ,pb:RetailBanking,pb:ABCAutoLoanBusiness,pb:CommercialRealEstate))
}