PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bas: <http://mindparabole.com/finance/basel_glossary#>

SELECT ?val ?concept ?Area ?Type ?Typename ?id
WHERE {
?Type owl:equivalentClass ?class ;rdfs:label ?Typename.
#FILTER(EXISTS{?Type rdfs:subClassOf pb:Model .})
FILTER(EXISTS{?Type rdfs:subClassOf pb:Model . } || EXISTS{?Type rdfs:subClassOf pb:Policy . })
?class owl:allValuesFrom|owl:someValuesFrom ?val; owl:onProperty ?prop.
FILTER(!bound(?val) = false)
OPTIONAL{?val owl:oneOf/rdf:rest*/rdf:first  ?concept}
?Type rdfs:subClassOf ?Area 
FILTER ( ?Area IN (pb:Model, pb:Policy))
#BIND(xsd:string("Model Type") AS ?Area)
bind(rand() AS ?id)
}