PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.mindparabole.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT  ?Focus_Area (SUM(?FA1) AS ?Commercial_Service) (SUM(?FA2) AS ?Corp_Finance) 
(SUM(?FA3) AS ?Transportation_and_International_Finance)(SUM(?FA4) AS ?Consumer_Banking)
(SUM(?FA5) AS ?Equipment_Finance)(SUM(?FA6) AS ?Finance)
(SUM(?FA7) AS ?Risk)(SUM(?FA8) AS ?Reg_Reporting)
(SUM(?FA9) AS ?Treasury)(SUM(?FA10) AS ?Tax)
(SUM(?FA11) AS ?Risk_Management_Group)(SUM(?FA12) AS ?Vendor_Finance)
(SUM(?FA13) AS ?Transportation_Finance)(SUM(?FA14) AS ?Trade_Finance)
(SUM(?FA15) AS ?Home_Lending)(SUM(?FA16) AS ?CIT_Bank)
(SUM(?FA17) AS ?Credit_Administration)(SUM(?FA18) AS ?Investment_Securities)
WHERE{
{SELECT  ?FA  ?Focus_Area  (COUNT(?person) AS ?num)
WHERE{
?person rdf:type pb:Person .
?person pb:has_Functional_Area  ?FA.
?person pb:has_Focus_Area ?Focus_Area}

GROUP BY ?FA  ?Focus_Area }
BIND(IF(?FA =  pb:Commercial_Services,?num,0) AS ?FA1)
BIND(IF(?FA = pb:Corporate_Finance,?num,0) AS ?FA2)
BIND(IF(?FA = pb:Transportation_and_International_Finance,?num,0) AS ?FA3)
BIND(IF(?FA = pb:Consumer_Banking,?num,0) AS ?FA4)
BIND(IF(?FA = pb:Equipment_Finance,?num,0) AS ?FA5)
BIND(IF(?FA = pb:Finance,?num,0) AS ?FA6)
BIND(IF(?FA = pb:Risk,?num,0) AS ?FA7)
BIND(IF(?FA = pb:Regulatory_Reporting,?num,0) AS ?FA8)
BIND(IF(?FA = pb:Treasury,?num,0) AS ?FA9)
BIND(IF(?FA = pb:Tax,?num,0) AS ?FA10)
BIND(IF(?FA = pb:Risk_Management_Group,?num,0) AS ?FA11)
BIND(IF(?FA = pb:Vendor_Finance,?num,0) AS ?FA12)
BIND(IF(?FA = pb:Transportation_Finance,?num,0) AS ?FA13)
BIND(IF(?FA = pb:Trade_Finance,?num,0) AS ?FA14)
BIND(IF(?FA = pb:Home_Lending,?num,0) AS ?FA15)
BIND(IF(?FA = pb:CIT_Bank,?num,0) AS ?FA16)
BIND(IF(?FA = pb:Credit_Administration,?num,0) AS ?FA17)
BIND(IF(?FA = pb:Investment_Securities,?num,0) AS ?FA18)}
GROUP BY  ?Focus_Area

