PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.mindparabole.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT ?Report_Field ?Status
WHERE{
?Report_Field mpb-root-main:hasReportFieldStatus ?Status.
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name

}