PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.mindparabole.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX smf: <http://topbraid.org/sparqlmotionfunctions#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aml:<http://nextangles.com/tradefinance/AMLInvestigationData#>
PREFIX cdd:<http://nextangles.com/tradefinance/CommDocument#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX cloc:<http://nextangles.com/tradefinance/CommercialLetterOfCredit#>
PREFIX com:<http://nextangles.com/tradefinance/Common#>
PREFIX trxn:<http://nextangles.com/tradefinance/Transaction#>
PREFIX alert:<http://nextangles.com/TradeFinance/Alert#>
PREFIX rule:<http://nextangles.com/Temp/Rule#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>

select  ?name ?role
where{
?user rdf:type pb:Person .
?user rdfs:label ?name .
?user pb:hasRole ?rol .
?rol rdfs:label ?role.
FILTER(?name = "Betsy Walters")
}
