PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX CDE:<http://www.mindparabole.com/ontology/finance/CDE/CriticalDataElements#>
SELECT ?Functional_Area (COUNT(?CDE) AS ?CDEs_definded_by_Specific_Corp_Function) (COUNT(?CDE2) AS ?Number_of_Shared_CDEs)
WHERE{

{SELECT *
WHERE{
?CDE CDE:CDE_has_Corp_Func ?FA2.
?FA2 rdfs:label ?Functional_Area .
FILTER(?CDE =?cde)

FILTER(?num =1)
{SELECT  ?cde (COUNT(?FA)AS ?num)
WHERE{
?cde CDE:CDE_has_Corp_Func ?FA.
}
GROUP BY ?cde }
}}
UNION
{SELECT * 
WHERE{
?CDE2 CDE:CDE_has_Corp_Func ?FA2.
?FA2 rdfs:label ?Functional_Area.
 }}}
GROUP BY ?Functional_Area
