PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?uri ?con ?concept ?Area ?connections ?mprp ?id
?pro  ?Product  ?seg ?Segment
where {
{select *
where {
{?con rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?con pb:hasModel ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Model") as ?Area)}
union
{?con rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?con pb:hasReport ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Report") AS ?Area)
}
union
{?con rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?con pb:hasPolicy ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
bind(xsd:string ("Policy") as ?Area)}
UNION
{?con rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?con pb:ConcepthasDataElement ?mprp.
bind(xsd:string ("Data Element") as ?Area)}
union
{?a rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?a pb:hasRelatedConcept ?mprp.
bind(xsd:string ("Related Concept") as ?Area)}
}}
?con rdfs:label ?concept .
BIND(xsd:string(CONCAT(afn:namespace(?con),afn:localname(?con))) AS ?uri)
?mprp rdfs:label ?connections .
bind(rand() AS ?id).

FILTER (?uri = "http://mindparabole.com/finance/fasb_concepts#AccountingAdjustment")

}

