PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/Bank_Main#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?labelReportSchedule (COUNT (?status) as ?identifiedGap) ((152/152) as ?TechLoadToReportStatus)
WHERE {
 	?schedule rdf:type mpb-root-main:ReportSchedule .
 	?schedule rdfs:label ?labelReportSchedule .
 	?schedule mpb-root-main:hasReportSub_Schedule ?sub_schedule .
 	?sub_schedule rdfs:label ?labelSub_Schedule .
 	?sub_schedule mpb-root-main:hasReportField ?reportField .
 	?reportField mpb-root-main:hasReportFieldStatus ?status .
FILTER (?status IN (mpb-root-main:ReportField_Status_DataGapIdentified)).
}
GROUP BY ?labelReportSchedule
