PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?mprp ?Component ?ComponentType ?conceptName ?Product ?Segment
where {
{select *
where {
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasModel ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Model") as ?ComponentType)}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasReport ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Report") AS ?ComponentType)
}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasPolicy ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
bind(xsd:string ("Policy") as ?ComponentType)}
UNION
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:ConcepthasDataElement ?mprp.
bind(xsd:string ("Data Element") as ?ComponentType)}
}}
?concept rdfs:label ?conceptName .
?mprp rdfs:label ?Component .
FILTER(?mprp = pb:MMLGDModel)
bind(rand() AS ?id).

}

