PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


select ?mprp ?conceptName ?segl ?prol ?id
where {
{select *
where {
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasModel ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasReport ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.

}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasProcedure ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf cst:FASBConcept .
?concept pb:hasPolicy ?mprp .
?mprp pb:hasSegment ?seg.
?seg pb:hasProduct ?pro.
}

}}
?concept rdfs:label ?conceptName .
?mprp rdfs:label ?connections .
?seg rdfs:label ?segl.
?pro rdfs:label ?prol.
FILTER(?mprp =pb:CCPDModel)

bind(rand() AS ?id).

}