PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX pnc:<http://mindparabole.com/finance/pnc_cecl#>
PREFIX cst:<http://mindparabole.com/finance/cecl_structure#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX bas: <http://mindparabole.com/finance/basel_glossary#>


select ?uri ?mprp ?Component ?ComponentType ?concept  ?conceptName ?pro ?Product ?seg ?Segment ?id
where {
{select *
where {
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf ?sub.
FILTER(?sub IN(cst:FASBConcept))
?concept pb:hasModel ?mprp .
MINUS{?mprp rdf:type pb:BaselModel}
?mprp pb:hasSegment ?seg.
?seg rdf:type ?segtype.
FILTER(?segtype = pb:BankASegments)
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Model") as ?ComponentType)}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf ?sub .
FILTER(?sub IN(cst:FASBConcept))
?concept pb:hasReport ?mprp .
?mprp pb:hasSegment ?seg.
?seg rdf:type ?segtype.
FILTER(?segtype = pb:BankASegments)
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
BIND(xsd:string("Report") AS ?ComponentType)
}
union
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf ?sub.
FILTER(?sub IN(cst:FASBConcept))
?concept pb:hasPolicy ?mprp .
MINUS{?mprp rdf:type pb:BaselPolicy}
?mprp pb:hasSegment ?seg.
?seg rdf:type ?segtype.
FILTER(?segtype = pb:BankASegments)
?seg pb:hasProduct ?pro.
?pro rdfs:label ?Product.
?seg rdfs:label ?Segment.
bind(xsd:string ("Policy") as ?ComponentType)}
UNION
{?concept rdf:type ?conclass .
?conclass rdfs:subClassOf ?sub .
FILTER(?sub IN(cst:FASBConcept))
?concept pb:ConcepthasDataElement ?mprp.
bind(xsd:string ("Data_Element") as ?ComponentType)}
}}
?concept rdfs:label ?conceptName .
?mprp rdfs:label ?Component .
BIND(xsd:string(CONCAT(afn:namespace(?mprp),afn:localname(?mprp))) as ?uri)
FILTER(?uri = $$FILTERS$$)
#FILTER(?uri = "http://www.mindparabole.com/ontology/finance/Parabole-Model#MMPDModel")
bind(rand() AS ?id).

}