PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/CIT_Main#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX CDE:<http://parabole.com/Coarys/CriticalDataElements#>
SELECT ?Month  ?Corp_Function (COUNT(?cde) AS ?Number)
WHERE {
VALUES ?month{1 2 3 4 5 6 7 8 9 10 11 12}

  ?cde  rdf:type CDE:Critical_Data_Elements. 
  ?cde CDE:CDE_has_Corp_Func ?FA.
?FA rdfs:label ?Corp_Function.    
  ?cde CDE:CDE_added_on_Date ?Adddate.
   BIND(replace(?Adddate,"_","-") AS ?Date2)
   BIND(xsd:date(?Date2) AS ?Addedon_Date)
  ?cde CDE:CDE_Removed_Date ?Remdate.
  BIND(replace(?Remdate,"_","-") AS ?Date3)
   BIND(xsd:date(?Date3) AS ?Removedon_Date)
FILTER(month(?Addedon_Date)<=?month && ?month <= month(?Removedon_Date) )
 BIND (
      IF(?month = 1, 01, 
       IF(?month = 2, 02,
        IF(?month = 3, 03,
         IF(?month = 4, 04,
          IF(?month = 5, 05,
           IF(?month = 6, 06,
            IF(?month = 7, 07, 
            IF(?month = 8,08,
            IF(?month = 9,09,
            IF(?month = 10,10,
            IF(?month = 11,11,
            IF(?month = 12, 12,"Unknown")
      ))))))))))) AS ?Month)
  }
  GROUP BY ?Month  ?Corp_Function
  ORDER BY ?Month