PREFIX mpb-root-main: <http://www.mindparabole.com/ontology/finance/MPBRoot_Main#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cit:<http://www.mindparabole.com/ontology/finance/CIT_Main#>
PREFIX CDE:<http://parabole.com/Coarys/CriticalDataElements#>
PREFIX mt:<http://www.mindparabole.com/meeting#>
PREFIX pb:<http://www.mindparabole.com/ontology/finance/Parabole-Model#>
PREFIX mpb-fin-main-ccar-14q:<http://www.mindparabole.com/ontology/finance/FRY-14Q_Main#>
PREFIX mpb-root-main-crm:<http://www.mindparabole.com/ontology/finance/CreditRiskManagement_Main#>
PREFIX mpb-fin-main-ccar:<http://www.mindparabole.com/ontology/finance/CCAR_Main#>
PREFIX Y14DB_Main:<http://www.nextangles.com/ontology/finance/Y14DB_Main#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT  ?Schedule_Name
(COUNT(?Report_Field) AS ?Num_of_Fields_Completed) 
(COUNT(?Report_Field2) AS ?Num_of_Field_with_Issue)
(COUNT(?Report_Field3) AS ?Num_of_Pass_Validation_Rule)
(COUNT(?Report_Field4) AS ?Num_Of_Fields_Mandatory) 
(COUNT(?Report_Field5) AS ?Num_Of_Feilds_Assumption)
WHERE{
{SELECT *
WHERE{
?Report_Field  mpb-root-main:hasReportFieldStatus ?Status.
FILTER(?Status = "Complete"^^xsd:string)
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
FILTER(?Schedule = mpb-fin-main-ccar:Sch_H_Wholesale_Risk)
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name

}}
UNION
{SELECT  *
WHERE{
?Report_Field2 cit:RFhasIssue ?Has_Issue.
FILTER(?Has_Issue = "Yes"^^xsd:string)
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field2.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
FILTER(?Schedule = mpb-fin-main-ccar:Sch_H_Wholesale_Risk)
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name

}}
UNION
{SELECT  *
WHERE{
?Report_Field3 cit:PassValidationRule ?Pass_Validation_Rule.
FILTER(?Pass_Validation_Rule ="Yes"^^xsd:string || ?Pass_Validation_Rule = "N/A"^^xsd:string)
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field3.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
FILTER(?Schedule = mpb-fin-main-ccar:Sch_H_Wholesale_Risk)
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name

}}
UNION
{SELECT  *
WHERE{
?Report_Field4  mpb-root-main:isReportFieldMandatory  ?Mandatory_Or_Optional.
FILTER( ?Mandatory_Or_Optional = "Mandatory"^^xsd:string)
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field4.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
FILTER(?Schedule = mpb-fin-main-ccar:Sch_H_Wholesale_Risk)
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name

}}

UNION
{SELECT *
WHERE{
?Report_Field5  cit:hasAssumptions ?Assumptions
FILTER(?Assumptions = "Test"^^xsd:string)
?Sub_Schedule  mpb-root-main:hasReportField ?Report_Field5.
?Sub_Schedule rdfs:label ?Sub_Schedule_Name.
?Sub_Schedule mpb-root-main:isPartOfReportSchedule ?Schedule.
FILTER(?Schedule = mpb-fin-main-ccar:Sch_H_Wholesale_Risk)
?Schedule rdfs:label ?Schedule_Name.
?Schedule mpb-root-main:isPartOfReport ?Report.
?Report rdfs:label ?Report_Name.
}}
}
GROUP BY  ?Schedule_Name


